### ISSUE TITLE
Failed test unit still show as passed

### ISSUE THREAD

**Issue by i-shm** [Release-Candidate/vscode-ocaml-alcotest-test-adapter#1]
When I run the tests with `dune test` from the command line, the test unit fails, but it still shows as passing in Test Explorer (I clicked `run tests` again):

![image](https://user-images.githubusercontent.com/66583620/224217190-159e86dd-c3ca-4007-aa48-f1b74a718c40.png)
![image](https://user-images.githubusercontent.com/66583620/224217213-a513b520-3820-4388-bd77-d9a1919c55ae.png)

---

I use `failwith` in `test_case` related function to indicate that a test failed (on line `101` I intentionally use `failwith` which throws an error):
![image](https://user-images.githubusercontent.com/66583620/224217725-73cf4728-7654-4125-b0b7-f781279ebcd0.png)

When I click `show output` to view the output, I can see that the relevant test failed:
![image](https://user-images.githubusercontent.com/66583620/224218035-633dee2f-f2fb-4ee7-a325-a49c6a32635e.png)

- Version of the extension: 0.3.0
- Version of VS Code: 1.76.1
- OS: Linux (openSUSE Tumbleweed x86_64)

---

- Whether Alcotest does not recommend using failwith to report a test failure?

**Comment by Release-Candidate** [comment]
Thanks for your bug report, I can reproduce your problem.

The error parser does not yet recognize the format of an exception raised by `failwith`, because it does expect to get a message `[exception]` instead of `[failure]`. I'll fix that as soon as possible and make a new version (my plan is doing that today).

As a temporary workaround you could use `raise` with an exception, like
```ocaml
exception ParseError of string

let failwithTmp msg = raise (ParseError msg) 
```
